# fly.toml app configuration file generated for sistemainventario-damp-rain-7384 on 2025-07-03T18:28:05-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sistemainventario-damp-rain-7384'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
